/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package EU_6

class App {
    val greeting: String
        get() {
            return "Hello World for Verfahren&Werkzeuge EA 6!"
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
}
